### ISSUE TITLE
How can I get the kernel default config ?

### ISSUE THREAD

**Issue by Jack-Kingdom** [scaleway/image-centos#23]
Hello everyone, I want to update linux kernel to latest. But I can't fetch centos default kernel config.

Error thrown when I run `make localmodconfig`:
```
No config file found at scripts/kconfig/streamline_config.pl line 124.
make[1]: *** [localmodconfig] Error 2
make: *** [localmodconfig] Error 2
```
And folder `/boot/config` is empty.

How can I get the kernel default config ?

**Comment by danhawker** [comment]
@Jack-Kingdom 
Not quite what you are after, but if you  zcat out `/proc/config.gz` this contains the compressed config for the present running kernel.
eg
```
[root@scw-2a025d ~]# zcat /proc/config.gz | grep SELINUX
CONFIG_SECURITY_SELINUX=y
CONFIG_SECURITY_SELINUX_BOOTPARAM=y
CONFIG_SECURITY_SELINUX_BOOTPARAM_VALUE=0
CONFIG_SECURITY_SELINUX_DISABLE=y
CONFIG_SECURITY_SELINUX_DEVELOP=y
CONFIG_SECURITY_SELINUX_AVC_STATS=y
CONFIG_SECURITY_SELINUX_CHECKREQPROT_VALUE=1
# CONFIG_DEFAULT_SECURITY_SELINUX is not set
```

**Comment by Jack-Kingdom** [comment]
@danhawker 
Yeah, I have tried. But this file not exist on my vps.
Thanks for your help.

**Comment by justinclift** [comment]
@Jack-Kingdom Is this still happening for you?

When I look for `/proc/config.gz` on a new c1 instance with CentOS 7, it shows up:

```
# ls -la /proc/config.gz 
-r--r--r-- 1 root root 23869 Jan 16 22:11 /proc/config.gz
```

**Comment by Jack-Kingdom** [comment]
@justinclift Yes, I found it. Thank you!
