### ISSUE TITLE
update to centos 7 1708 ? 

### ISSUE THREAD

**Issue by arpu** [scaleway/image-centos#24]
when will the update be ready?

**Comment by justinclift** [comment]
As a data point, on a new Paris C1 instance today the CentOS 7 version as installed was:

```
# cat /etc/redhat-release 
Derived from Red Hat Enterprise Linux 7.2 (Source)
```

After running yum update, it's:

```
# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core)
```

So, although the initial install image isn't 1708, it is shortly afterwards if you run yum update. :smile:

Does that help?

**Comment by arpu** [comment]
ohh thx for this information!

yes this helps a lot

**Comment by justinclift** [comment]
Awesome. :smile:

Be aware there's a small bug in the /etc/yum.repos.d/CentOS-Base.repo file that comes pre-installed, which stops yum update from working correctly.  It's pretty easy to fix, and there's a Pull Request here with the change needed:

&nbsp; &nbsp; https://github.com/scaleway/image-centos/pull/26/files

With that fix in place, yum update works properly. :smile:
