### ISSUE TITLE
update to centos 8 

### ISSUE THREAD

**Issue by arpu** [scaleway/image-centos#39]
are there any work on new centos 8 images?

**Comment by agravelot** [comment]
AFAIK CentOS does not provide any official upgrade guide, it's strongly recommended to start with a brand-new installation.

**Comment by arpu** [comment]
but there is no new centos 8 image for scaleway

**Comment by gene1wood** [comment]
Ya, what would it take to extend the code here to provision a CentOS 8 Scaleway base image? Is any work being done on this at Scaleway or should the community take this effort up and try to PR something here?

**Comment by kkmuffme** [comment]
Please people, update it finally, it's been released more than 6 months ago

**Comment by arpu** [comment]
ping @superseed  any news on this?

**Comment by plfiorini** [comment]
It's clear at this point that Scaleway supports only Ubuntu images

**Comment by gene1wood** [comment]
[Scaleway supports Ubuntu 20.04 7 days after it comes out](https://blog.scaleway.com/2020/ubuntu-20-04-lts-now-available/), we're waiting now going on 7 months. So weird. 

The product marketing manager at Scaleway [says that the update to CentOS 8 will come "later this year" and that the reason for the delay is that their users prefer Ubuntu](https://twitter.com/thomasschmit/status/1255965938551324672)

**Comment by karibou** [comment]
Hello,

It is not a matter of preference, but technical complexity. Unlike the
Ubuntu Cloud images, Centos does not provide an image that is UEFI
bootable. So extra work is required to get a valid Centos 8 image going
(ref https://bugzilla.redhat.com/show_bug.cgi?id=1507860*)*

Work on this image is moving forward and I'm hoping to be able to deliver
something in the coming weeks.

Kind regards,

...Louis

**Comment by plfiorini** [comment]
Thanks for your reply, do you know if Fedora has the same problem?
It's still at 29 but 32 got released a few days ago.

**Comment by gene1wood** [comment]
> I'm hoping to be able to deliver something in the coming weeks.

That's fantastic!

**Comment by karibou** [comment]
Hello,
We have just announced public availability of the CentOS 8.1 image on our platform.
Enjoy !
...Louis

**Comment by gene1wood** [comment]
@karibou Thank you! Is the code for this image in a different repo? Or just hasn't been committed yet? I only ask as this repo appears to still only have CentOS 7 in it.

For users, here are the `fr-par-1` image details

```
{
  "id": "bfaca3da-692a-4cae-8243-5522f8044b94",
  "name": "CentOS 8",
  "organization": "51b656e3-4865-41e8-adbc-0c45bdd780db",
  "root_volume": {
    "id": "e58765e2-6320-4b04-ac24-c824a6154b5d",
    "name": "centos_8:volume-0",
    "volume_type": "l_ssd",
    "size": 10000000000
  },
  "extra_volumes": {},
  "public": true,
  "arch": "x86_64",
  "creation_date": "2020-06-23T11:16:03.494980+00:00",
  "modification_date": "2020-06-23T11:16:03.494980+00:00",
  "default_bootscript": null,
  "from_server": null,
  "state": "available",
  "zone": "fr-par-1"
}
```

and the `nl-ams-1` image details

```
{
  "id": "f9738a60-939c-4d87-b9a2-7968e4878f50",
  "name": "CentOS 8",
  "organization": "51b656e3-4865-41e8-adbc-0c45bdd780db",
  "root_volume": {
    "id": "3ac8bf38-11a6-41e8-9391-8b188fd16fb5",
    "name": "centos_8:volume-0",
    "volume_type": "l_ssd",
    "size": 10000000000
  },
  "extra_volumes": {},
  "public": true,
  "arch": "x86_64",
  "creation_date": "2020-06-23T11:18:06.089179+00:00",
  "modification_date": "2020-06-23T11:18:06.089179+00:00",
  "default_bootscript": null,
  "from_server": null,
  "state": "available",
  "zone": "nl-ams-1"
}
```

**Comment by karibou** [comment]
@gene1wood New images are no longer being built using the method present in this repository.
We are now taking the official cloud images from Centos and Ubuntu and doing as little modifications as needed to have them run on Scaleway.

There are discussions currently going on opening the new method to the public or providing an interface for users to build their own images using our new pipeline.

Stay tuned !
...Louis

**Comment by gene1wood** [comment]
> There are discussions currently going on opening the new method to the public or providing an interface for users to build their own images using our new pipeline.

Excellent, great context, really appreciate it.
